### PR TITLE
Added new buffer to shader to accept a particle color - particles now us...

### PR DESCRIPTION
**Pull request by FlexMonkey**
...e combinations of this source color themselves depending on type (i.e. RGB in give three colors: RBG, GRB and BGR).

Linked frequency to shader input color and tinkered with parameters

### CODE REVIEW

**Comment by FlexMonkey** [comment]
Hi Aure,

I've linked the particle color to the frequency and done some other tinkering, let me know what you think.

Cheers,

Simon

**Comment by aure** [comment]
I love it!   The only thing that is a little bit off-putting is the color changing so quickly.

**Comment by FlexMonkey** [comment]
Agreed - I tried to smooth it be using that averaging code, but it wasn't
as smooth as it could be. I'll have a tinker.

I cut a little work-in-progress screen recording:
https://www.youtube.com/watch?v=I-l8RALIoA4

Simon

On 5 April 2015 at 10:03, Aurelius Prochazka <notifications@github.com>
wrote:

> I love it! The only thing that is a little bit off-putting is the color
> changing so quickly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/audiokit/MetalParticles/pull/1#issuecomment-89736734>.
>



-- 
*flexmonkey.co.uk <http://flexmonkey.co.uk> | @FlexMonkey
<https://twitter.com/FlexMonkey> | +44 (0) 7973 669691*

**Comment by aure** [comment]
This is so amazing with music!  Can we go full screen?

Aure

**Comment by FlexMonkey** [comment]
... no problem.

Actually, that sudden color change has been fixed with a slightly hacky
solution:

       particleLab.particleColor = ParticleColor(

            R: (particleLab.particleColor.R * 9 +
targetColors.redComponent) / 10,

            G: (particleLab.particleColor.G * 9 +
targetColors.greenComponent) / 10,

            B: (particleLab.particleColor.B * 9 +
targetColors.blueComponent) / 10,

            A: 1.0)

...it feels wrong, but it works :)

Simon

On 5 April 2015 at 10:26, Aurelius Prochazka <notifications@github.com>
wrote:

> This is so amazing with music! Can we go full screen?
>
> Aure
>
> On Sun, Apr 5, 2015 at 2:12 AM, simon gladman <notifications@github.com>
> wrote:
>
> > Agreed - I tried to smooth it be using that averaging code, but it wasn't
> > as smooth as it could be. I'll have a tinker.
> >
> > I cut a little work-in-progress screen recording:
> > https://www.youtube.com/watch?v=I-l8RALIoA4
> >
> > Simon
> >
> > On 5 April 2015 at 10:03, Aurelius Prochazka <notifications@github.com>
> > wrote:
> >
> > > I love it! The only thing that is a little bit off-putting is the color
> > > changing so quickly.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/audiokit/MetalParticles/pull/1#issuecomment-89736734
> > >.
> > >
> >
> >
> >
> > --
> > *flexmonkey.co.uk <http://flexmonkey.co.uk> | @FlexMonkey
> > <https://twitter.com/FlexMonkey> | +44 (0) 7973 669691*
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/audiokit/MetalParticles/pull/1#issuecomment-89738245
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/audiokit/MetalParticles/pull/1#issuecomment-89741202>.
>



-- 
*flexmonkey.co.uk <http://flexmonkey.co.uk> | @FlexMonkey
<https://twitter.com/FlexMonkey> | +44 (0) 7973 669691*

**Comment by aure** [comment]
Make a pull request when you can and I'll take a look, but its past my bed
time so it might not be until 6-7 hours from now.

Aure

**Comment by FlexMonkey** [comment]
Sleep well.

Best wishes,

Simon

On 5 April 2015 at 10:41, Aurelius Prochazka <notifications@github.com>
wrote:

> Make a pull request when you can and I'll take a look, but its past my bed
> time so it might not be until 6-7 hours from now.
>
> Aure
>
> On Sun, Apr 5, 2015 at 2:28 AM, simon gladman <notifications@github.com>
>
> wrote:
>
> > ... no problem.
> >
> > Actually, that sudden color change has been fixed with a slightly hacky
> > solution:
> >
> > particleLab.particleColor = ParticleColor(
> >
> > R: (particleLab.particleColor.R * 9 +
> > targetColors.redComponent) / 10,
> >
> > G: (particleLab.particleColor.G * 9 +
> > targetColors.greenComponent) / 10,
> >
> > B: (particleLab.particleColor.B * 9 +
> > targetColors.blueComponent) / 10,
> >
> > A: 1.0)
> >
> > ...it feels wrong, but it works :)
> >
> > Simon
> >
> > On 5 April 2015 at 10:26, Aurelius Prochazka <notifications@github.com>
> > wrote:
> >
> >
> > > This is so amazing with music! Can we go full screen?
> > >
> > > Aure
> > >
> > > On Sun, Apr 5, 2015 at 2:12 AM, simon gladman <
> notifications@github.com>
> > > wrote:
> > >
> > > > Agreed - I tried to smooth it be using that averaging code, but it
> > wasn't
> > > > as smooth as it could be. I'll have a tinker.
> > > >
> > > > I cut a little work-in-progress screen recording:
> > > > https://www.youtube.com/watch?v=I-l8RALIoA4
> > > >
> > > > Simon
> > > >
> > > > On 5 April 2015 at 10:03, Aurelius Prochazka <
> notifications@github.com
> > >
> > > > wrote:
> > > >
> > > > > I love it! The only thing that is a little bit off-putting is the
> > color
> > > > > changing so quickly.
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > >
> https://github.com/audiokit/MetalParticles/pull/1#issuecomment-89736734
> > > > >.
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > *flexmonkey.co.uk <http://flexmonkey.co.uk> | @FlexMonkey
> > > > <https://twitter.com/FlexMonkey> | +44 (0) 7973 669691*
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > https://github.com/audiokit/MetalParticles/pull/1#issuecomment-89738245
> > > >.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/audiokit/MetalParticles/pull/1#issuecomment-89741202
> > >.
> >
> > >
> >
> >
> >
> > --
> > *flexmonkey.co.uk <http://flexmonkey.co.uk> | @FlexMonkey
> > <https://twitter.com/FlexMonkey> | +44 (0) 7973 669691*
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/audiokit/MetalParticles/pull/1#issuecomment-89741916
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/audiokit/MetalParticles/pull/1#issuecomment-89744583>.
>



-- 
*flexmonkey.co.uk <http://flexmonkey.co.uk> | @FlexMonkey
<https://twitter.com/FlexMonkey> | +44 (0) 7973 669691*

**Pull request merged**
